spring:
  application:
    name: HotelBookingSystem
  datasource:
    url: jdbc:h2:file:./data/hotel_db;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: simple
  mail:
    host: smtp.gmail.com
    port: 587
    username: umeshgupta050104@gmail.com
    password: your_16_character_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

resilience4j:
  ratelimiter:
    instances:
      api:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0

app:
  jwt:
    secret: 926D96C90030DD58429D2751AC1BDBBC926D96C90030DD58429D2751AC1BDBBC
    expirationMs: 86400000

razorpay:
  key:
    id: rzp_test_SaXL0fheGFoGLq
    secret: w1Dw3D9c3xK6KJOKh0ZU524L

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8085